import { AuditLogService } from "./services/AuditLogService.js";
import { ConfigValidationService } from "./services/ConfigValidationService.js";
import { FileService } from "./services/FileService.js";
import { PluginService } from "./services/PluginService.js";
import { AuthService } from "./services/AuthService.js";
import { MultiServerRuntimeService } from "./services/MultiServerRuntimeService.js";
import { ServerInstallService } from "./services/ServerInstallService.js";
import { ServerRegistryService } from "./services/ServerRegistryService.js";
import { ServerAdminService } from "./services/ServerAdminService.js";
import { ServerSettingsService } from "./services/ServerSettingsService.js";
import { VersionCatalogService } from "./services/VersionCatalogService.js";
import { ModService } from "./services/ModService.js";
import { BackupService } from "./services/BackupService.js";
import { JobsService } from "./services/JobsService.js";
import { MetricsService } from "./services/MetricsService.js";
import { NodeService } from "./services/NodeService.js";
import { NotificationService } from "./services/NotificationService.js";
import { PlatformDataService } from "./services/PlatformDataService.js";
import { TokenService } from "./services/TokenService.js";
import { NodeExecutionService } from "./services/NodeExecutionService.js";
import type { WebSocketHub } from "./services/WebSocketHub.js";

export type AppContext = {
  runtime: MultiServerRuntimeService;
  settings: ServerSettingsService;
  servers: ServerRegistryService;
  auth: AuthService;
  installer: ServerInstallService;
  admin: ServerAdminService;
  versionCatalog: VersionCatalogService;
  audit: AuditLogService;
  files: FileService;
  plugins: PluginService;
  mods: ModService;
  configValidation: ConfigValidationService;
  platform: PlatformDataService;
  nodes: NodeService;
  notifications: NotificationService;
  backups: BackupService;
  jobs: JobsService;
  metrics: MetricsService;
  tokens: TokenService;
  nodeExec: NodeExecutionService;
  ws: WebSocketHub;
};
